// SVG constants
var SVG_WIDTH = 970;
var SVG_HEIGHT = 400;

// Bar Chart Constants
var MARGIN_TOP = 20;
var MARGIN_LEFT = 40;
var MARGIN_BOTTOM = 20;
var MARGIN_RIGHT = 130; 

// Bar Constants
var HOVER_INTENSITY = 0.7;

// Legend Constants
var LEGEND_WIDTH = 100;
var LEGEND_CONTENT_HEIGHT = 130;
var LEGEND_MARGIN_LEFT = 10;
var LEGEND_MARGIN_TOP = 10;
var LEGEND_CONTENT_MARGIN_TOP = 10;
var LEGEND_CONTENT_MARGIN_LEFT = 10;
var LEGEND_ELEMENT_HEIGHT = 25;
var LEGEND_ELEMENT_WIDTH = 20;
var LEGEND_ELEMENT_SEPARATION = 2;
var LEGEND_TITLE_MARGIN_LEFT = 25;
var LEGEND_TEXT_ELEMENT_START_X = 70;
var LEGEND_TEXT_ELEMENT_START_Y = 8;
